default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_blog_development

test:
  <<: *default
  database: photo_blog_test

production:
  <<: *default
  database: photo_blog_production
  username: photo_blog
  password: <%= ENV["PHOTO_BLOG_DATABASE_PASSWORD"] %>
